import type { editor } from 'monaco-editor';

/**
 * Custom Monaco editor themes matching the Agent-X purple/cyan OKLCH palette.
 *
 * Light: "agentx-light" — soft lavender background with purple/cyan accents
 * Dark:  "agentx-dark"  — deep indigo background with vibrant purple/cyan accents
 */

export const agentxLight: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '8E8EA0', fontStyle: 'italic' },
    { token: 'keyword', foreground: '7C3AED' },
    { token: 'keyword.control', foreground: '7C3AED' },
    { token: 'storage', foreground: '7C3AED' },
    { token: 'storage.type', foreground: '7C3AED' },
    { token: 'string', foreground: '0891B2' },
    { token: 'string.escape', foreground: '0E7490' },
    { token: 'number', foreground: 'D97706' },
    { token: 'constant', foreground: 'D97706' },
    { token: 'type', foreground: '2563EB' },
    { token: 'type.identifier', foreground: '2563EB' },
    { token: 'class', foreground: '2563EB' },
    { token: 'interface', foreground: '2563EB' },
    { token: 'function', foreground: '6D28D9' },
    { token: 'function.declaration', foreground: '6D28D9' },
    { token: 'variable', foreground: '334155' },
    { token: 'variable.predefined', foreground: 'D97706' },
    { token: 'parameter', foreground: '475569' },
    { token: 'property', foreground: '0D9488' },
    { token: 'operator', foreground: '64748B' },
    { token: 'delimiter', foreground: '64748B' },
    { token: 'tag', foreground: '7C3AED' },
    { token: 'attribute.name', foreground: '0891B2' },
    { token: 'attribute.value', foreground: '0D9488' },
    { token: 'meta.tag', foreground: '7C3AED' },
    { token: 'regexp', foreground: 'E11D48' },
  ],
  colors: {
    'editor.background': '#F8F7FC',
    'editor.foreground': '#1E1B4B',
    'editor.lineHighlightBackground': '#F0EEFA',
    'editor.selectionBackground': '#DDD6FE80',
    'editor.inactiveSelectionBackground': '#E8E5F5',
    'editorLineNumber.foreground': '#A5A3C0',
    'editorLineNumber.activeForeground': '#7C3AED',
    'editorCursor.foreground': '#7C3AED',
    'editorIndentGuide.background': '#E8E5F0',
    'editorIndentGuide.activeBackground': '#C4B5FD',
    'editorBracketMatch.background': '#DDD6FE50',
    'editorBracketMatch.border': '#A78BFA',
    'editor.findMatchBackground': '#A5F3FC60',
    'editor.findMatchHighlightBackground': '#DDD6FE40',
    'editorWidget.background': '#F8F7FC',
    'editorWidget.border': '#E2E0F0',
    'editorSuggestWidget.background': '#F8F7FC',
    'editorSuggestWidget.border': '#E2E0F0',
    'editorSuggestWidget.selectedBackground': '#EDE9FE',
    'scrollbarSlider.background': '#C4B5FD30',
    'scrollbarSlider.hoverBackground': '#C4B5FD50',
    'scrollbarSlider.activeBackground': '#C4B5FD70',
  },
};

export const agentxDark: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6B6B8D', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'A78BFA' },
    { token: 'keyword.control', foreground: 'A78BFA' },
    { token: 'storage', foreground: 'A78BFA' },
    { token: 'storage.type', foreground: 'A78BFA' },
    { token: 'string', foreground: '22D3EE' },
    { token: 'string.escape', foreground: '67E8F9' },
    { token: 'number', foreground: 'FBBF24' },
    { token: 'constant', foreground: 'FBBF24' },
    { token: 'type', foreground: '60A5FA' },
    { token: 'type.identifier', foreground: '60A5FA' },
    { token: 'class', foreground: '60A5FA' },
    { token: 'interface', foreground: '60A5FA' },
    { token: 'function', foreground: 'C084FC' },
    { token: 'function.declaration', foreground: 'C084FC' },
    { token: 'variable', foreground: 'E2E8F0' },
    { token: 'variable.predefined', foreground: 'FBBF24' },
    { token: 'parameter', foreground: 'CBD5E1' },
    { token: 'property', foreground: '2DD4BF' },
    { token: 'operator', foreground: '94A3B8' },
    { token: 'delimiter', foreground: '94A3B8' },
    { token: 'tag', foreground: 'A78BFA' },
    { token: 'attribute.name', foreground: '22D3EE' },
    { token: 'attribute.value', foreground: '2DD4BF' },
    { token: 'meta.tag', foreground: 'A78BFA' },
    { token: 'regexp', foreground: 'FB7185' },
  ],
  colors: {
    'editor.background': '#161332',
    'editor.foreground': '#E2E0F0',
    'editor.lineHighlightBackground': '#1E1B4B',
    'editor.selectionBackground': '#7C3AED40',
    'editor.inactiveSelectionBackground': '#312E5A',
    'editorLineNumber.foreground': '#4C4A6D',
    'editorLineNumber.activeForeground': '#A78BFA',
    'editorCursor.foreground': '#A78BFA',
    'editorIndentGuide.background': '#2A2750',
    'editorIndentGuide.activeBackground': '#7C3AED60',
    'editorBracketMatch.background': '#7C3AED30',
    'editorBracketMatch.border': '#A78BFA',
    'editor.findMatchBackground': '#0891B240',
    'editor.findMatchHighlightBackground': '#7C3AED25',
    'editorWidget.background': '#1A1740',
    'editorWidget.border': '#2A2750',
    'editorSuggestWidget.background': '#1A1740',
    'editorSuggestWidget.border': '#2A2750',
    'editorSuggestWidget.selectedBackground': '#312E5A',
    'scrollbarSlider.background': '#7C3AED20',
    'scrollbarSlider.hoverBackground': '#7C3AED35',
    'scrollbarSlider.activeBackground': '#7C3AED50',
  },
};
